import:
  - ~/.config/alacritty/alacritty-keybinds.yml
  - ~/.config/alacritty/green-on-black.yml
env:
  TERM: 'alacritty'

# Font settings
font:
    normal:
      family: JetBrainsMonoNL Nerd Font Mono
    bold:
      style: SemiBold
    size: 16

# Window settings
window:
    dimensions:
      columns: 85
      lines: 23
    padding:
        x: 12
        y: 12
    decorations: none
    opacity: .95
    startup_mode: Windowed
    position: 
        x: 0
        y: 0

# Change cursor style
cursor:
    style:
        blinking: Always
    thickness: 0.1
    blink_timeout: 0
    vi_mode_style: 'Block'
