
[cursor]
blink_timeout = 0
thickness = 0.1
vi_mode_style = "Block"

[cursor.style]
blinking = "Always"

[env]
TERM = "alacritty"

[font]
size = 17
offset = { x = -1, y = 0 }

[font.bold]
style = "SemiBold"

[font.normal]
family = "CommitMono Nerd Font"

[window]
decorations = "none"
opacity = 0.96
blur = true
startup_mode = "Windowed"

[window.dimensions]
columns = 85
lines = 23

[window.padding]
x = 12
y = 12

[window.position]
x = 0
y = 0

[general]
import = [
  "/home/alquimista/.config/alacritty/alacritty-keybinds.toml",
  "/home/alquimista/.config/alacritty/green-on-black.toml",
]
