
# Green on Black scheme
colors: 
  # Default colors
  primary:
    background: '#030303'
    foreground: '#FF9400'
      # foreground: '#b98000'

  # Normal colors
  normal:
    black:   '#171421'
    red:     '#C01C28'
    green:   '#26A269'
    yellow:  '#A2734C'
    blue:    '#12488B'
    magenta: '#A347BA'
    cyan:    '#2AA1B3'
    white:   '#D0CFCC'

  # Bright colors
  bright:
    black:   '#5E5C64'
    red:     '#F66151'
    green:   '#33DA7A'
    yellow:  '#E9AD0C'
    blue:    '#2A7BDE'
    magenta: '#C061CB'
    cyan:    '#33C7DE'
    white:   '#FFFFFF'
