# Japanesque color scheme
colors: 
  primary:
    foreground: "#f7f6ec"
    background: "#1e1e1e"
  normal:
    black: "#343935"
    red: "#cf3f61"
    green: "#7bb75b"
    yellow: "#e9b32a"
    blue: "#4c9ad4"
    magenta: "#a57fc4"
    cyan: "#389aad"
    white: "#fafaf6"

  bright:
    black: "#595b59"
    red: "#d18fa6"
    green: "#767f2c"
    yellow: "#78592f"
    blue: "#135979"
    magenta: "#604291"
    cyan: "#76bbca"
    white: "#b2b5ae"
