format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$python\
$cmd_duration\
$line_break\
$character"""

# Timeout for commands executed by starship (in milliseconds).
command_timeout = 3000

# Disable the blank line at the start of the prompt
add_newline = false

[username]
show_always = true
style_user = "bold green"
format = '[$user: ]($style)'

[directory]
style = "bold green"
truncation_length = 2
truncation_symbol = "…/"
home_symbol = "~"

[character]
success_symbol = "[\\$](bold green)"
error_symbol = "[\\$](red)"
vimcmd_symbol = "[\\$](yellow)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = '[* $all_status$ahead_behind ]($style)'
# format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "bright-black"
conflicted = "$ "
modified = '!${count} '
staged = '+${count} '
untracked = '?${count} '
renamed = '» '
deleted = "-${count} "
stashed = "≡ "

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\)'
style = "bright-black"

[cmd_duration]
disabled = true
format = "[$duration]($style) "
style = "yellow"
min_time = 5
show_milliseconds = true

[python]
format = '[(\($virtualenv\))]($style) '
style = "bright-black"

[fill]
symbol = ' '
disabled = true

[os]
disabled = false
format = "[$symbol ]($style)"
style = "bg:#3B4252"

[os.symbols]
Fedora = "󰣛"
Debian = "󰣚"
Ubuntu = ""
Windows = ""
