# e %h/.config/BraveSoftware/Brave-Browser/Default/Code\ Cache/js                 - - - 7d
# e %h/.config/BraveSoftware/Brave-Browser/Default/Cache/Cache_Data               - - - 7d

e %h/.cache/BraveSoftware/Brave-Browser/Default/Cache/Cache_Data                - - - 7d
e %h/.cache/BraveSoftware/Brave-Browser/Default/Code\x20Cache/js                  - - - 7d
e %h/.config/BraveSoftware/Brave-Browser/Default/GPUCache                       - - - 7d

# e %h/.config/BraveSoftware/Brave-Browser/Default/Service\ Worker/CacheStorage   - - - 7d
e %h/.config/BraveSoftware/Brave-Browser/Default/Service\x20Worker/ScriptCache    - - - 7d

e %h/.config/Code/CachedData                                                    - - - 7d
