[/]
active-hint=false
active-hint-border-width=uint32 1
focus-up=['<Super>Up']
gap-inner=uint32 1
gap-outer=uint32 1
mosaic-cached-state=''
mosaic-monitor-down=@as []
mosaic-monitor-left=@as []
mosaic-monitor-right=@as []
mosaic-monitor-up=@as []
mosaic-workspace-down=@as []
mosaic-workspace-up=@as []
mouse-cursor-follows-active-window=false
resize-grow-down=@as []
resize-grow-left=['<Shift><Alt><Super>Left']
resize-grow-right=@as []
resize-grow-up=@as []
resize-shrink-down=@as []
resize-shrink-left=['<Shift><Alt><Super>Right']
resize-shrink-right=@as []
resize-shrink-up=@as []
smart-gaps=false
tile-by-default=true
tile-swap-down=@as []
tile-swap-left=@as []
tile-swap-right=@as []
tile-swap-up=@as []
