--enable-features=AcceleratedVideoDecodeLinuxGL,AcceleratedVideoDecodeLinuxZeroCopyGL,AcceleratedVideoEncoder,VaapiIgnoreDriverChecks
--disk-cache-dir=/tmp/BraveSoftware/Brave-Browser
--enable-zero-copy
--disable-features=CalculateNativeWinOcclusion
--disable-background-networking
--enable-low-end-device-mode
# --ozone-platform=x11
