--enable-features=AcceleratedVideoDecodeLinuxZeroCopyGL,AcceleratedVideoEncoder,VaapiIgnoreDriverChecks,UseMultiPlaneFormatForHardwareVideo
--enable-features=enable-gpu-isolation
# --disk-cache-dir=/tmp/BraveSoftware/Brave-Browser
--enable-zero-copy
--enable-gpu-rasterization
--ignore-gpu-blocklist
--enable-features=HeuristicMemorySaver:threshold_percent/85/minimum_minutes_in_background/30
--disable-background-networking
# --enable-low-end-device-mode
# --ozone-platform=auto
