--enable-features=AcceleratedVideoDecodeLinuxZeroCopyGL,AcceleratedVideoEncoder,VaapiIgnoreDriverChecks,UseMultiPlaneFormatForHardwareVideo
--enable-features=enable-gpu-isolation
# --disk-cache-dir=/tmp/BraveSoftware/Brave-Browser
--enable-zero-copy
--enable-gpu-rasterization
--ignore-gpu-blocklist
--renderer-process-limit=16
--disable-background-networking
# --enable-low-end-device-mode
# --ozone-platform=auto
