#Spacebar icons     󰨞  󰈭  󰵅

[appindicator]
custom-icons=@a(sss) []

[blur-my-shell]
color-and-noise=false

[blur-my-shell/applications]
blur=false
blur-on-overview=false

[blur-my-shell/dash-to-dock]
blur=false
customize=false
override-background=true

[blur-my-shell/dash-to-panel]
blur-original-panel=false

[blur-my-shell/lockscreen]
customize=false

[blur-my-shell/panel]
blur=true
brightness=0.59999999999999998
customize=false
override-background=true
sigma=30
static-blur=true
style-panel=2
unblur-in-overview=true

[caffeine]
countdown-timer=0
indicator-position-max=1
restore-state=true
screen-blank='never'
toggle-state=true
user-enabled=true

[dash-to-dock]
apply-custom-theme=false
autohide-in-fullscreen=false
background-color='rgb(128,128,128)'
background-opacity=0.64000000000000001
custom-background-color=true
custom-theme-shrink=true
dash-max-icon-size=64
dock-fixed=false
dock-position='BOTTOM'
height-fraction=0.78000000000000003
hide-tooltip=false
hot-keys=false
intellihide-mode='ALL_WINDOWS'
isolate-locations=true
max-alpha=0.80000000000000004
middle-click-action='minimize'
preferred-monitor=-2
preferred-monitor-by-connector='eDP-1'
pressure-threshold=50.0
preview-size-scale=0.20999999999999999
scroll-to-focused-application=true
shift-click-action='minimize'
shift-middle-click-action='launch'
shortcut=['<Super>n']
shortcut-text='<Super>n'
show-apps-at-top=false
show-icons-emblems=false
show-running=true
show-show-apps-button=true
show-windows-preview=false
transparency-mode='DEFAULT'
workspace-agnostic-urgent-windows=true

[just-perfection]
accessibility-menu=false
activities-button=false
activities-button-icon-monochrome=false
activities-button-label=false
animation=1
app-menu=false
app-menu-icon=true
clock-menu-position=0
clock-menu-position-offset=0
controls-manager-spacing-size=0
dash-icon-size=64
hot-corner=true
notification-banner-position=1
panel=true
panel-arrow=false
panel-button-padding-size=0
panel-corner-size=1
panel-in-overview=true
panel-size=29
ripple-box=false
search=true
show-apps-button=true
startup-status=0
theme=false
weather=false
window-demands-attention-focus=true
window-picker-icon=false
workspace=true
workspace-peek=false
workspace-popup=false
workspaces-in-app-grid=false
world-clock=false

[pop-shell]
active-hint=false
active-hint-border-radius=uint32 1
gap-inner=uint32 1
gap-outer=uint32 1
pop-workspace-down=@as []
pop-workspace-up=@as []
show-title=true
tile-by-default=false

[rounded-window-corners]
black-list=['org.wezfurlong.wezterm']
border-color=(0.0, 0.0, 0.0, 1.0)
border-width=0
custom-rounded-corner-settings=@a{sv} {}
enable-preferences-entry=true
focused-shadow={'vertical_offset': 10, 'horizontal_offset': 0, 'blur_offset': 33, 'spread_radius': 8, 'opacity': 100}
global-rounded-corner-settings={'padding': <{'left': <uint32 1>, 'right': <uint32 1>, 'top': <uint32 1>, 'bottom': <uint32 1>}>, 'keep_rounded_corners': <{'maximized': <true>, 'fullscreen': <false>}>, 'border_radius': <uint32 12>, 'smoothing': <uint32 0>, 'enabled': <true>}
settings-version=uint32 5
skip-libadwaita-app=false
tweak-kitty-terminal=false
unfocused-shadow={'horizontal_offset': 0, 'vertical_offset': 0, 'blur_offset': 25, 'spread_radius': -1, 'opacity': 89}

[space-bar/appearance]
active-workspace-font-size=14
active-workspace-font-size-active=true
active-workspace-font-size-user=14
active-workspace-font-weight='700'
active-workspace-padding-h=8
active-workspace-padding-v=0
empty-workspace-font-size=14
empty-workspace-font-weight='700'
empty-workspace-padding-h=8
empty-workspace-padding-v=0
inactive-workspace-font-size=14
inactive-workspace-font-weight='700'
inactive-workspace-padding-h=8
inactive-workspace-padding-v=0
workspace-margin=4
workspaces-bar-padding=0

[space-bar/behavior]
indicator-style='workspaces-bar'
position-index=0
smart-workspace-names=false
toggle-overview=false

[space-bar/shortcuts]
enable-activate-workspace-shortcuts=true
enable-move-to-workspace-shortcuts=false

[vitals]
fixed-widths=false
hot-sensors=['__network-rx_max__', '_processor_frequency_', '_processor_usage_', '_system_uptime_', '__temperature_avg__', '__fan_avg__']
position-in-panel=3
update-time=3
