[/]
con-split-horizontal=['<Super>z']
con-split-layout-toggle=['<Super>g']
con-split-vertical=@as []
con-stacked-layout-toggle=@as []
con-tabbed-layout-toggle=['<Super>s']
con-tabbed-showtab-decoration-toggle=['<Control><Alt>y']
focus-border-toggle=['<Super>x']
prefs-tiling-toggle=['<Super>y']
window-focus-down=['<Super>j']
window-focus-left=['<Super>h']
window-focus-right=['<Super>l']
window-focus-up=['<Super>k']
window-gap-size-decrease=['<Control><Super>minus']
window-gap-size-increase=['<Control><Super>plus']
window-move-down=['<Shift><Super>j']
window-move-left=['<Shift><Super>h']
window-move-right=['<Shift><Super>l']
window-move-up=['<Shift><Super>k']
window-resize-bottom-decrease=['<Alt><Super>i']
window-resize-bottom-increase=['<Control><Super>u']
window-resize-left-decrease=['<Alt><Super>o']
window-resize-left-increase=['<Control><Super>y']
window-resize-right-decrease=['<Alt><Super>y']
window-resize-right-increase=['<Control><Super>o']
window-resize-top-decrease=['<Alt><Super>u']
window-resize-top-increase=['<Control><Super>i']
window-snap-center=@as []
window-snap-one-third-left=@as []
window-snap-one-third-right=@as []
window-snap-two-third-left=@as []
window-snap-two-third-right=@as []
window-swap-down=['<Control><Super>j']
window-swap-last-active=['<Super>Return']
window-swap-left=['<Control><Super>h']
window-swap-right=['<Control><Super>l']
window-swap-up=['<Control><Super>k']
window-toggle-always-float=['<Shift><Super>g']
window-toggle-float=['<Control><Super>g']
workspace-active-tile-toggle=@as []
