[/]
close=['<Super>q']
minimize=['<Super>comma']
move-to-monitor-down=@as []
move-to-monitor-up=@as []
move-to-workspace-left=['<Alt><Super>k']
move-to-workspace-right=['<Alt><Super>j']
switch-to-workspace-left=['<Alt><Super>h']
switch-to-workspace-right=['<Alt><Super>l']
