[/]
control-center=['<Super>F1']
custom-keybindings=['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/']
email=['<Super>e']
help=@as []
home=['<Super>f']
logout=@as []
rotate-video-lock-static=@as []
screensaver=['<Super>Escape']
terminal=['<Super>t']
www=['<Super>b']

[custom-keybindings/custom1]
binding='<Super>t'
command='ghostty'
name='ghostty'

[custom-keybindings/custom3]
binding='<Super>i'
command='gtk-launch wezterm.desktop'
name='Wezterm'
